import type { ReactNode } from "react";
import { Bell, BookOpen, ChartBar, ChartLine, GearSix, House, ListChecks, ListMagnifyingGlass, PaperPlaneTilt, Play, ShieldCheck, UsersThree, Wrench, X } from "@phosphor-icons/react";
import { Button } from "./primitives";

const icons = { overview: House, accounts: UsersThree, automation: Play, ads: ListMagnifyingGlass, analytics: ChartLine, rules: ListChecks, notifications: Bell, launch: PaperPlaneTilt, maintenance: Wrench, "system-users": ShieldCheck };
export function AccountShell({ children, navigation, onNavigate, runtimeEnabled, runtimeBusy, canControl, onToggleRuntime, userName, onLogout, error, onDismissError, activeKey = "accounts", pageTitle = "账户管理", headerActions }: {
  children: ReactNode; navigation: Array<{ key: string; label: string; section: string }>;
  onNavigate: (key: string) => void; runtimeEnabled: boolean; runtimeBusy: boolean; canControl: boolean; onToggleRuntime: () => void;
  userName: string; onLogout: () => void; error: string | null; onDismissError: () => void; activeKey?: string; pageTitle?: string; headerActions?: ReactNode;
}) {
  return <div className="production-ui p-shell"><aside className="p-sidebar"><div className="p-brand"><span className="p-brand-mark">TK</span><div><strong>TK Automation</strong><small>广告运营工作台</small></div></div><nav aria-label="主导航">{navigation.map((item, index) => { const Icon = icons[item.key as keyof typeof icons] ?? GearSix; const active = item.key === activeKey; return <div key={item.key}>{(index === 0 || navigation[index - 1]?.section !== item.section) && <div className="p-nav-section">{item.section}</div>}<button type="button" className={`p-nav-item ${active ? "is-active" : ""}`} aria-current={active ? "page" : undefined} onClick={() => onNavigate(item.key)}><Icon size={19} />{item.label}</button></div>; })}</nav><div className="p-sidebar-bottom"><button className={`p-nav-item ${activeKey === "manual" ? "is-active" : ""}`} type="button" onClick={() => onNavigate("manual")}><BookOpen size={19} />操作手册</button><div className="p-local-status"><i />本地自动化引擎</div></div></aside><main className="p-main"><header className="p-topbar"><span><ChartBar size={17} />工作空间 <span className="p-breadcrumb-slash">/</span> {pageTitle}</span><div className="p-header-actions">{headerActions}<button className="p-runtime-control" type="button" disabled={!canControl || runtimeBusy} onClick={onToggleRuntime} title={runtimeEnabled ? "暂停全局自动化" : "恢复全局自动化"}><i className={`p-dot ${runtimeEnabled ? "healthy" : "warning"}`} />{runtimeBusy ? "更新中…" : runtimeEnabled ? "全局自动化运行中" : "全局自动化已暂停"}</button><span className="p-user-avatar">{userName.slice(0, 1)}</span><span>{userName}</span><Button tone="quiet" onClick={onLogout}>退出</Button></div></header><div className="p-content">{error && <div className="p-feedback" role="alert"><span>{error}</span><Button tone="quiet" aria-label="关闭错误提示" onClick={onDismissError}><X size={16} /></Button></div>}{children}</div></main></div>;
}
