/*
 * Product icon vocabulary.  Business pages keep their existing semantic icon
 * names while this adapter makes Phosphor the only icon implementation used
 * by the web app.
 */
export {
  Pulse as Activity,
  Warning as AlertTriangle,
  Archive as ArchiveRestore,
  ArrowRight,
  Prohibit as Ban,
  ChartBar as BarChart3,
  BellRinging as BellRing,
  BookOpen,
  Calendar as CalendarDays,
  Check,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretUp as ChevronUp,
  WarningCircle as CircleAlert,
  CurrencyCircleDollar as CircleDollarSign,
  Gauge as CircleGauge,
  XCircle as CircleX,
  XCircle,
  Clock as Clock3,
  CopySimple as CopyPlus,
  Database as DatabaseBackup,
  DownloadSimple as Download,
  ArrowSquareOut as ExternalLink,
  FileLock as FileClock,
  FileXls as FileSpreadsheet,
  Warning as FileWarning,
  Gauge,
  ClockCounterClockwise as History,
  Tray as Inbox,
  Info,
  Key,
  StackSimple as Layers3,
  SquaresFour as LayoutDashboard,
  Link as Link2,
  ListChecks,
  ListDashes as ListFilter,
  SignIn as LogIn,
  Envelope as Mail,
  Megaphone,
  ChatText as MessageSquareText,
  Moon,
  Pause,
  PencilSimple as Pencil,
  Play,
  Plug as PlugZap,
  Plus,
  ArrowClockwise as RefreshCcw,
  ArrowClockwise as RefreshCw,
  RocketLaunch as Rocket,
  ArrowCounterClockwise as RotateCcw,
  FloppyDisk as Save,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  GearSix as Settings2,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Sun,
  CloudSun as Sunrise,
  Trash as Trash2,
  TrendUp as TrendingUp,
  UploadSimple as Upload,
  UserGear as UserCog,
  User as UserRound,
  UsersThree as Users,
  X,
  Copy,
} from "@phosphor-icons/react";

export { Key as KeyRound } from "@phosphor-icons/react";
